name: Publish
defaults:
  run:
    shell: bash

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Get Package Version
        id: package-version
        run: node -p "'version='+require('./package').version" >> $GITHUB_OUTPUT

      - name: Publish Package
        run: |
          npm version ${{ steps.package-version.outputs.version }} --no-git-tag-version
          npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
